name: Database Migrations Testing Pipeline
run-name: Test DB Migrations in ${{ inputs.ENV_NAME }} environment by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: AWS Region name to use as a target environment
        type: string
        required: true
        default: us-east-2
      ENV_NAME:
        description: Name of the target environment
        type: choice
        required: true
        options:
          - dev
          - stg
          - uat
          - prd
        default: prd
      AUTODELETE:
        description: Set to true to terminate the instance after migrations
        type: boolean
        default: false
        required: true

env:
  AWS_DEFAULT_REGION: us-east-2
  NODE_VERSION: 16.17.0
  KUBECTL_VERSION: 1.27.2

jobs:
  build:
    name: Test DB Migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get RDS endpoint
        id: get_rds_endpoint
        continue-on-error: true
        run: |
          echo "GET RDS ENDPOINT"

      - name: Create an artifact
        id: create_artifact
        continue-on-error: true
        run: echo "CREATE ARTIFACT"

      - name: Install NPM dependencies
        id: install_deps
        continue-on-error: true
        run: echo "INSTALL DEPS"

      - name: Run migrations
        id: run_migrations
        continue-on-error: true
        run: echo "RUN MIGRATIONS"

      - name: Delete RDS for migrations
        if: >-
          ${{
            steps.get_rds_endpoint.outcome != 'success' ||
            steps.create_artifact.outcome != 'success' ||
            steps.install_deps.outcome != 'success' ||
            steps.run_migrations.outcome != 'success' ||
            inputs.AUTODELETE
          }}
        run: echo "DELETE RDS FOR MIGRATIONS"
