name: "libvips install test"

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'Environment name'
        required: true
        default: 'dev'
        options:
          - dev

jobs:
  libvips-install-test:
    if: inputs.SKIP_TESTS == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Install vips
      - name: Install libvips
        run:
          sudo snap install -y libvips
