name: "Pass ENV var "

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'Environment name'
        required: true
        default: 'staging'
        options:
          - staging
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version
        id: bump-version
        run: |
          TAG=$(echo VERSION-1-2-3-45)
      - name: Set output
        id: set-output
        run: echo "IMAGE_TAG=$TAG" >> $GITHUB_OUTPUT

  bump_version_dev:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ needs.build.outputs.IMAGE_TAG }}
    steps:
      - run: echo "bump_version_dev"

  notify:
    name: Notify on Slack
    if: always()
    needs: bump_version_dev
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.bump_version_dev.outputs.VERSION }}
    steps:
      - run: echo ${{ env.VERSION }}

