name: 'Dev Test Env vars'

on:
    workflow_dispatch:
        inputs:
            ENVIRONMENT:
                type: environment
                description: 'Environment name'
                required: true
                default: 'dev'
                options:
                    - dev
jobs:
    build:
        if: inputs.SKIP_BUILD == false
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Get env vars
              run: |
                echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
                echo "GH_REF_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  file: ./Dockerfile
                  context: .
                  push: false
                  tags: |
                    REGISTRY/REPOSITORY:${{ env.SHORT_SHA }}-${{ env.GH_REF_NAME }}

            - name: Get full gh sha
              run: echo ${GITHUB_SHA}

            - name: Get short gh sha
              run: echo ${GITHUB_SHA::7}

