on: push
name: Slack Notification Demo
jobs:
  successedJob:
    name: Successed Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls -la
    - uses: rtCamp/action-slack-notify@v2
      name: Send slack notification
      if: ${{ failure() }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "FAILURE...."
        SLACK_COLOR: ${{ job.status }}

    - uses: rtCamp/action-slack-notify@v2
      name: Send slack notification
      if: ${{ success() }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "SUCCESS"
        SLACK_COLOR: ${{ job.status }}
  failedJob:
    name: Failed Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cat test.txt
      name: Send slack notification
      if: ${{ failure() }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "FAILURE...."
        SLACK_COLOR: ${{ job.status }}

    - uses: rtCamp/action-slack-notify@v2
      name: Send slack notification
      if: ${{ success() }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "SUCCESS"
        SLACK_COLOR: ${{ job.status }}
  
