name: 'Dev Test Env vars'

on:
    workflow_dispatch:
        inputs:
            ENVIRONMENT:
                type: environment
                description: 'Environment name'
                required: true
                default: 'dev'
                options:
                    - dev
jobs:
    build:
        if: inputs.SKIP_BUILD == false
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build and push
              uses: docker/build-push-action@v4
              # env:
              #   GITHUB_REF_NAME: ${ github.ref_name }
              #   GITHUB_SHA: ${GITHUB_SHA::7}
              with:
                  file: ./Dockerfile
                  context: .
                  push: false
                  tags: |
                    type=raw,value=REGISTRY/REPOSITORY:${GITHUB_SHA::7}-${ github.ref_name }

            - name: Get full gh sha
              run: echo ${GITHUB_SHA}

            - name: Get short gh sha
              run: echo ${GITHUB_SHA::7}

