name: 'Dev Test Env vars'

on:
    workflow_dispatch:
        inputs:
            ENVIRONMENT:
                type: environment
                description: 'Environment name'
                required: true
                default: 'dev'
                options:
                    - dev
jobs:
    build:
        if: inputs.SKIP_BUILD == false
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Check python
              run: python --version
